title: "Balham.org"
description: "The independent guide to Balham — discover local businesses, events, and history in SW12."
url: "https://balham.org"

remote_theme: mmistakes/minimal-mistakes@4.26.1

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-redirect-from

locale: en_GB

author:
  name: Balham.org
  email: hello@balham.org

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-YVD72VFTLW"

og_image: /images/map.webp  # Default social image

seo:
  twitter_card_type: summary_large_image

social:
  type: Organization
  name: Balham.org
  links:
    - https://github.com/balham.org
    - https://links.davecross.co.uk

atom_feed:
  hide: true

defaults:
  - scope:
      path: ""
    values:
      layout: single

collections:
  pages:
    output: true
    permalink: /:path/

